### PR TITLE
added jekyll

### PR DESCRIPTION
**Pull request by marc-hanheide**
I have managed to package up jekyll using [this method](https://gist.github.com/marc-hanheide/4ebea62ada0883ed84eb) and made them available on our own repository: 

```
precise|main|amd64: rubygem-blankslate 2.1.2.4                                                                                                          
precise|main|amd64: rubygem-celluloid 0.16.0                                                                                                            
precise|main|amd64: rubygem-classifier-reborn 2.0.1                                                                                                     
precise|main|amd64: rubygem-coffee-script 2.3.0                                                                                                         
precise|main|amd64: rubygem-coffee-script-source 1.8.0                                                                                                  
precise|main|amd64: rubygem-colorator 0.1.0                                                                                                             
precise|main|amd64: rubygem-execjs 2.2.2                                                                                                                
precise|main|amd64: rubygem-fast-stemmer 1.0.2                                                                                                          
precise|main|amd64: rubygem-ffi 1.9.6                                                                                                                   
precise|main|amd64: rubygem-hitimes 1.2.2                                                                                                               
precise|main|amd64: rubygem-jekyll 2.4.0                                                                                                                
precise|main|amd64: rubygem-jekyll-coffeescript 1.0.1                                                                                                   
precise|main|amd64: rubygem-jekyll-gist 1.1.0                                                                                                           
precise|main|amd64: rubygem-jekyll-paginate 1.1.0                                                                                                       
precise|main|amd64: rubygem-jekyll-sass-converter 1.2.1                                                                                                 
precise|main|amd64: rubygem-jekyll-watch 1.1.1                                                                                                          
precise|main|amd64: rubygem-kramdown 1.5.0                                                                                                              
precise|main|amd64: rubygem-liquid 2.6.1                                                                                                                
precise|main|amd64: rubygem-listen 2.7.11                                                                                                               
precise|main|amd64: rubygem-mercenary 0.3.4                                                                                                             
precise|main|amd64: rubygem-parslet 1.5.0                                                                                                               
precise|main|amd64: rubygem-posix-spawn 0.3.9                                                                                                           
precise|main|amd64: rubygem-pygments.rb 0.6.0                                                                                                           
precise|main|amd64: rubygem-rb-fsevent 0.9.4                                                                                                            
precise|main|amd64: rubygem-rb-inotify 0.9.5                                                                                                            
precise|main|amd64: rubygem-redcarpet 3.2.0                                                                                                             
precise|main|amd64: rubygem-safe-yaml 1.0.4                                                                                                             
precise|main|amd64: rubygem-sass 3.4.6                                                                                                                  
precise|main|amd64: rubygem-timers 4.0.1                                                                                                                
precise|main|amd64: rubygem-toml 0.1.2                                                                                                                  
precise|main|amd64: rubygem-yajl-ruby 1.1.0 
```

So, now we can base robblog on this new dependency, configured in our own rosdep, added in https://github.com/strands-project/rosdistro/pull/85

This pull request adds this `run_depend` to make sure the package will be released with the dependency in place.

### CODE REVIEW

**Comment by marc-hanheide** [comment]
come on @hawesie, this is awesome stuff, merge it!

**Comment by marc-hanheide** [comment]
oh, and release it

**Comment by hawesie** [comment]
Sorry, this is lower priority than the scheduling stuff, so it won't get done this week.

**Comment by hawesie** [comment]
@marc-hanheide I can't release this as `bloom-release` chokes on the `rubygem-jekyll` dependency. I have our rosdistro in rosdep, but I don't see the packages above:

```
nah@ubuntu:~/releasing/robblog$ rosdep db | grep ruby
ruby1.9.3 -> ruby1.9.3
hoe -> ruby-hoe
nokogiri -> ruby-nokogiri
ruby -> ruby1.8-dev libruby1.8 rubygems1.8
rosruby_common -> ros-hydro-rosruby-common
rosruby_messages -> ros-hydro-rosruby-messages
rosruby_tutorials -> ros-hydro-rosruby-tutorials
rosruby -> ros-hydro-rosruby
rosruby_actionlib -> ros-hydro-rosruby-actionlib
flexmock -> ruby-flexmock
facets -> ruby-facets
ruby-sass -> ruby-sass
```

I do have the packages available in `apt-cache` though.

**Comment by cdondrup** [comment]
Since @marc-hanheide might have no time, I can release this. I have `rubygem-jekyll -> rubygem-jekyll`. Will run bloom now.

**Comment by hawesie** [comment]
That would be cool, thanks. We can leave @marc-hanheide to puzzle out why I don't have it later.

**Comment by cdondrup** [comment]
PR is open: https://github.com/strands-project/rosdistro/pull/185

**Pull request merged**
